security:
    encoders:
        App\Entity\User:
            algorithm: auto

#    enable_authenticator_manager: true

    providers:
        user_provider:
            id: App\Security\Core\User\UserProvider

    firewalls:
        register:
            pattern: ^/api/users/register
            methods: [POST]
            security: false

        docs:
            pattern: ^/api/docs
            methods: [GET]
            security: false

        login:
            pattern: ^/api/users/login
            stateless: true
            anonymous: true
            provider: user_provider
            json_login:
                check_path: /api/users/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        getUsers:
            pattern: ^/api/users
            methods: [ GET ]
            security: false

        getUser:
            pattern: ^/api/users/.*
            methods: [ GET ]
            security: false

        getPhotos:
            pattern: ^/api/photos
            methods: [GET]
            security: false

        getPhoto:
            pattern: ^/api/photos/.*
            methods: [GET]
            security: false

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
