
#################################### USERS #########################################

POST http://localhost:250/api/users/register
Content-Type: application/json

{
  "name": "User",
  "email": "user@email.com",
  "password": "User@01"
}

####################

GET http://localhost:250/api/users/1

####################

GET http://localhost:250/api/users/login_check
Content-Type: application/json

{
  "username": "user@email.com",
  "password": "User@01"
}

####################