
#################################### USERS #########################################

POST http://localhost:250/api/users/register
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin@nodrizatech.com",
  "password": "Nodriza@01",
  "roles": [
    "ROLE_ADMIN"
  ]
}

####################

GET http://localhost:250/api/users/1

####################

GET http://localhost:250/api/users/login_check
Content-Type: application/json

{
  "username": "admin@nodrizatech.com",
  "password": "Nodriza@01"
}

####################