
#################################### USERS #########################################

POST http://localhost:250/api/users/register
Content-Type: application/json

{
  "name": "User",
  "email": "user@email.com",
  "password": "User@01"
}

####################

GET http://localhost:250/api/users

####################

GET http://localhost:250/api/users/4dc5f148-547c-4fb6-9082-b14b43a08130

####################

GET http://localhost:250/api/users/login_check
Content-Type: application/json

{
  "username": "user@email.com",
  "password": "User@01"
}

####################

PUT http://localhost:250/api/users/4dc5f148-547c-4fb6-9082-b14b43a08130
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUwNDQyODEsImV4cCI6MTYzMDIyODI4MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6IjRkYzVmMTQ4LTU0N2MtNGZiNi05MDgyLWIxNGI0M2EwODEzMCIsIm5hbWUiOiJVc2VyIn0.G1XUukhpPYeICDasMAZRfRpjzCEftbziMJc7LYOe-OzzHDJGiA75r8hfrW9EvVXOLPzgiD1xhJEe2HplvW_DcO52I27sSyRY6LKvrCRf0wr5p_9WnektD7Vk35q1roS82Pwcgd6yfvRCTRJpzgBcoXuENtBoIcoIwqvKUDFqsK-vboi4qJK_HaqmxlXikcqSREvOq2yOhqtfMVgUUovQLA7TdnokscNwqFlSuoKwXZApB_EKMQ5eIkmFSPMITH7_UFl1kcPgqOxhYG8yXnr4Z_OVMWG9MqztlGeQrAvc7ds0GBUgdpLmaJAvPRJ8yqjCkj0qUTABfUyfc3p560Y7YDsTTktf9mlqVmBcUuLwmVgX7AwcDAdR_qUQK-aF6V4s_rmCy2TQ7Orw3XR_DCL1NryH8cKG05yWD_x7oKLkkCqQuZwVAiM29xwU6DCG2ZY18UfnENDBJWBKMpgkDqwk8JReKk17NxSi2_RRzqGvKuYUIDEjc0upov_c5NSKisDZAM4WHBzcg4QO8lO6MqbuJU2WM_hp93ItRAT1uV0O3LOsKLgcva-XKIeCzaCGChdm9nzbFWqLMXmgailzxA3pjCUDsxeymkIY-NuAbARZypmXsXcjqJNfYVA1OYgPExzDfj8FhUgW1GYYfVHU0cg_V1zdcXhT8Y6kGRD_xZv7eqk

{
  "name": "updated"
}





#################################### Photos #########################################

POST http://localhost:250/api/photos/upload
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUwNDQyODEsImV4cCI6MTYzMDIyODI4MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6IjRkYzVmMTQ4LTU0N2MtNGZiNi05MDgyLWIxNGI0M2EwODEzMCIsIm5hbWUiOiJVc2VyIn0.G1XUukhpPYeICDasMAZRfRpjzCEftbziMJc7LYOe-OzzHDJGiA75r8hfrW9EvVXOLPzgiD1xhJEe2HplvW_DcO52I27sSyRY6LKvrCRf0wr5p_9WnektD7Vk35q1roS82Pwcgd6yfvRCTRJpzgBcoXuENtBoIcoIwqvKUDFqsK-vboi4qJK_HaqmxlXikcqSREvOq2yOhqtfMVgUUovQLA7TdnokscNwqFlSuoKwXZApB_EKMQ5eIkmFSPMITH7_UFl1kcPgqOxhYG8yXnr4Z_OVMWG9MqztlGeQrAvc7ds0GBUgdpLmaJAvPRJ8yqjCkj0qUTABfUyfc3p560Y7YDsTTktf9mlqVmBcUuLwmVgX7AwcDAdR_qUQK-aF6V4s_rmCy2TQ7Orw3XR_DCL1NryH8cKG05yWD_x7oKLkkCqQuZwVAiM29xwU6DCG2ZY18UfnENDBJWBKMpgkDqwk8JReKk17NxSi2_RRzqGvKuYUIDEjc0upov_c5NSKisDZAM4WHBzcg4QO8lO6MqbuJU2WM_hp93ItRAT1uV0O3LOsKLgcva-XKIeCzaCGChdm9nzbFWqLMXmgailzxA3pjCUDsxeymkIY-NuAbARZypmXsXcjqJNfYVA1OYgPExzDfj8FhUgW1GYYfVHU0cg_V1zdcXhT8Y6kGRD_xZv7eqk

{
  "archive": "ruta",
  "description": "aaa",
  "private": true,
  "user": "/api/users/4dc5f148-547c-4fb6-9082-b14b43a08130"
}

####################

GET http://localhost:250/api/photos

####################

GET http://localhost:250/api/photos/e2ee6ff5-ffab-4f91-9578-e902e6a8bac3

####################

POST http://localhost:250/api/photos/e2ee6ff5-ffab-4f91-9578-e902e6a8bac3/like
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUwNDQyODEsImV4cCI6MTYzMDIyODI4MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6IjRkYzVmMTQ4LTU0N2MtNGZiNi05MDgyLWIxNGI0M2EwODEzMCIsIm5hbWUiOiJVc2VyIn0.G1XUukhpPYeICDasMAZRfRpjzCEftbziMJc7LYOe-OzzHDJGiA75r8hfrW9EvVXOLPzgiD1xhJEe2HplvW_DcO52I27sSyRY6LKvrCRf0wr5p_9WnektD7Vk35q1roS82Pwcgd6yfvRCTRJpzgBcoXuENtBoIcoIwqvKUDFqsK-vboi4qJK_HaqmxlXikcqSREvOq2yOhqtfMVgUUovQLA7TdnokscNwqFlSuoKwXZApB_EKMQ5eIkmFSPMITH7_UFl1kcPgqOxhYG8yXnr4Z_OVMWG9MqztlGeQrAvc7ds0GBUgdpLmaJAvPRJ8yqjCkj0qUTABfUyfc3p560Y7YDsTTktf9mlqVmBcUuLwmVgX7AwcDAdR_qUQK-aF6V4s_rmCy2TQ7Orw3XR_DCL1NryH8cKG05yWD_x7oKLkkCqQuZwVAiM29xwU6DCG2ZY18UfnENDBJWBKMpgkDqwk8JReKk17NxSi2_RRzqGvKuYUIDEjc0upov_c5NSKisDZAM4WHBzcg4QO8lO6MqbuJU2WM_hp93ItRAT1uV0O3LOsKLgcva-XKIeCzaCGChdm9nzbFWqLMXmgailzxA3pjCUDsxeymkIY-NuAbARZypmXsXcjqJNfYVA1OYgPExzDfj8FhUgW1GYYfVHU0cg_V1zdcXhT8Y6kGRD_xZv7eqk

{
  "value": "dislike",
  "user": "/api/users/4dc5f148-547c-4fb6-9082-b14b43a08130"
}

####################

PUT http://localhost:250/api/photos/e2ee6ff5-ffab-4f91-9578-e902e6a8bac3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUwNDQyODEsImV4cCI6MTYzMDIyODI4MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6IjRkYzVmMTQ4LTU0N2MtNGZiNi05MDgyLWIxNGI0M2EwODEzMCIsIm5hbWUiOiJVc2VyIn0.G1XUukhpPYeICDasMAZRfRpjzCEftbziMJc7LYOe-OzzHDJGiA75r8hfrW9EvVXOLPzgiD1xhJEe2HplvW_DcO52I27sSyRY6LKvrCRf0wr5p_9WnektD7Vk35q1roS82Pwcgd6yfvRCTRJpzgBcoXuENtBoIcoIwqvKUDFqsK-vboi4qJK_HaqmxlXikcqSREvOq2yOhqtfMVgUUovQLA7TdnokscNwqFlSuoKwXZApB_EKMQ5eIkmFSPMITH7_UFl1kcPgqOxhYG8yXnr4Z_OVMWG9MqztlGeQrAvc7ds0GBUgdpLmaJAvPRJ8yqjCkj0qUTABfUyfc3p560Y7YDsTTktf9mlqVmBcUuLwmVgX7AwcDAdR_qUQK-aF6V4s_rmCy2TQ7Orw3XR_DCL1NryH8cKG05yWD_x7oKLkkCqQuZwVAiM29xwU6DCG2ZY18UfnENDBJWBKMpgkDqwk8JReKk17NxSi2_RRzqGvKuYUIDEjc0upov_c5NSKisDZAM4WHBzcg4QO8lO6MqbuJU2WM_hp93ItRAT1uV0O3LOsKLgcva-XKIeCzaCGChdm9nzbFWqLMXmgailzxA3pjCUDsxeymkIY-NuAbARZypmXsXcjqJNfYVA1OYgPExzDfj8FhUgW1GYYfVHU0cg_V1zdcXhT8Y6kGRD_xZv7eqk

{
  "description": "edited",
  "private": false
}

####################

DELETE http://localhost:250/api/photos/e2ee6ff5-ffab-4f91-9578-e902e6a8bac3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUwNDQyODEsImV4cCI6MTYzMDIyODI4MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6IjRkYzVmMTQ4LTU0N2MtNGZiNi05MDgyLWIxNGI0M2EwODEzMCIsIm5hbWUiOiJVc2VyIn0.G1XUukhpPYeICDasMAZRfRpjzCEftbziMJc7LYOe-OzzHDJGiA75r8hfrW9EvVXOLPzgiD1xhJEe2HplvW_DcO52I27sSyRY6LKvrCRf0wr5p_9WnektD7Vk35q1roS82Pwcgd6yfvRCTRJpzgBcoXuENtBoIcoIwqvKUDFqsK-vboi4qJK_HaqmxlXikcqSREvOq2yOhqtfMVgUUovQLA7TdnokscNwqFlSuoKwXZApB_EKMQ5eIkmFSPMITH7_UFl1kcPgqOxhYG8yXnr4Z_OVMWG9MqztlGeQrAvc7ds0GBUgdpLmaJAvPRJ8yqjCkj0qUTABfUyfc3p560Y7YDsTTktf9mlqVmBcUuLwmVgX7AwcDAdR_qUQK-aF6V4s_rmCy2TQ7Orw3XR_DCL1NryH8cKG05yWD_x7oKLkkCqQuZwVAiM29xwU6DCG2ZY18UfnENDBJWBKMpgkDqwk8JReKk17NxSi2_RRzqGvKuYUIDEjc0upov_c5NSKisDZAM4WHBzcg4QO8lO6MqbuJU2WM_hp93ItRAT1uV0O3LOsKLgcva-XKIeCzaCGChdm9nzbFWqLMXmgailzxA3pjCUDsxeymkIY-NuAbARZypmXsXcjqJNfYVA1OYgPExzDfj8FhUgW1GYYfVHU0cg_V1zdcXhT8Y6kGRD_xZv7eqk
