App\Entity\User:

  attributes:
    normalization_context:
      groups: [user_read]

  collectionOperations:

    get:
      method: GET
#      security: is_granted("USER_READ")
#      security_message: 'Wrong Permissions, You can not get the Users'

    register:
      method: POST
      path: /users/register
      controller: App\Api\Action\User\Register
      denormalization_context:
        groups: [ user_register ]
#      security_post_denormalize: is_granted("USER_REGISTER", object)
#      security_post_denormalize_message: 'Wrong Permissions, You can not register an User'
      openapi_context:
        summary: Register a new user

    login:
      method: POST
      route_name: api_login_check
      openapi_context:
        summary: Login a User
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    token:
                      type: string

  itemOperations:
    get:
      method: GET
#      security: is_granted("USER_READ")
#      security_message: 'Wrong Permissions, You can not get an User'

    put:
      method: PUT
#        security: is_granted("PHOTO_UPDATE")
#        security_message: 'Wrong Permissions, You can not update this User'
      denormalization_context:
        groups: [ user_update ]

  properties:
    services:
      subresource:
        resourceClass: App\Entity\Photo
        collection: true
        maxDepth: 1