App\Entity\User:

  attributes:
    normalization_context:
      groups: [user_read]

  collectionOperations:

    get: ~

    register:
      method: POST
      path: /users/register
      controller: App\Api\Action\User\Register
      denormalization_context:
        groups: [ user_register ]
      openapi_context:
        summary: Register a new user

    login:
      method: POST
      route_name: api_login_check
      openapi_context:
        summary: Login a User
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    token:
                      type: string

  itemOperations:
    get: ~

    put:
      method: PUT
      security: is_granted("USER_UPDATE", object)
      security_message: 'Wrong Permissions, You can not update this User'
      denormalization_context:
        groups: [ user_update ]

  properties:
    photos:
      subresource:
        resourceClass: App\Entity\Photo
        collection: true
        maxDepth: 1
    groups:
      subresource:
        resourceClass: App\Entity\Group
        collection: true
        maxDepth: 1