
#################################### Groups #########################################

POST http://localhost:250/api/groups/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUxMzE2NTYsImV4cCI6MTYzMDMxNTY1Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6ImIwMWVkMWVkLTlmMDYtNGYxMS05MjA1LTExY2JmMzIxOTkzNCIsIm5hbWUiOiJVc2VyIn0.p2TnBsOCyKQ2MvBe1ODtsbRDRpB7FsL0odFQwyUeAevt_iKSMg-MNeNQbLYmtgF4zxzPGgwBlartUIY7Cw7Vp_UUwiBcRAmK8SLZbZpvqyn0fcAGolA9nR-v5ev0yPenKC1iKi7C3K3j7oCwQb44YEKBflnQESSGt6KGeQUXipksO-8Gr9NjAuYe3nPEw_BIlHYw_ju-fnkpgV4r-25jzzxlHZQ20EZuwCi529JbiyyfZMYocqPLUx2u5MmjT0ZaS9SM06752r9JOKYv97Dt3I3lHbytprT6aztNk7DSi27wT2KbkNmXcn_9D4rYFFhUB6Y-FrFGLwq8Zp_BSgljroNpskeWL1ab9i2vblJNvDqbXWc0wVoXtr0Fp_ji71bYM7lK0HXsHTrCzRY61RvaZgbkQbafqnOYFS3A_jGuB8TgyLqJNiwhKw1WNUBYdUt5MDQ4wEwP0j1eI8_5iym8-fe__KlinalEa8MaN6WnfhSYvcAF7LVYPHBVbi1OhLMrV0_94iBd4lcQmMX6rkzMvaw8f6u7HtTc2CmQPVTbtP3OLH9Qt5gPAwUGpewIw0av4Vwym3_UdWkYcjGENBqoyj1-6CCN5sKVvX8PauvWcZc5yCD4OkNt9KC0CuTunLRQ2Ak2tK5qQY97v7iASGHdzzJYnxKpEERI7vyLI6uZmA8

{
  "name": "grupo",
  "owner": "/api/users/b01ed1ed-9f06-4f11-9205-11cbf3219934"
}

####################

GET http://localhost:250/api/groups
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUxMzE2NTYsImV4cCI6MTYzMDMxNTY1Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6ImIwMWVkMWVkLTlmMDYtNGYxMS05MjA1LTExY2JmMzIxOTkzNCIsIm5hbWUiOiJVc2VyIn0.p2TnBsOCyKQ2MvBe1ODtsbRDRpB7FsL0odFQwyUeAevt_iKSMg-MNeNQbLYmtgF4zxzPGgwBlartUIY7Cw7Vp_UUwiBcRAmK8SLZbZpvqyn0fcAGolA9nR-v5ev0yPenKC1iKi7C3K3j7oCwQb44YEKBflnQESSGt6KGeQUXipksO-8Gr9NjAuYe3nPEw_BIlHYw_ju-fnkpgV4r-25jzzxlHZQ20EZuwCi529JbiyyfZMYocqPLUx2u5MmjT0ZaS9SM06752r9JOKYv97Dt3I3lHbytprT6aztNk7DSi27wT2KbkNmXcn_9D4rYFFhUB6Y-FrFGLwq8Zp_BSgljroNpskeWL1ab9i2vblJNvDqbXWc0wVoXtr0Fp_ji71bYM7lK0HXsHTrCzRY61RvaZgbkQbafqnOYFS3A_jGuB8TgyLqJNiwhKw1WNUBYdUt5MDQ4wEwP0j1eI8_5iym8-fe__KlinalEa8MaN6WnfhSYvcAF7LVYPHBVbi1OhLMrV0_94iBd4lcQmMX6rkzMvaw8f6u7HtTc2CmQPVTbtP3OLH9Qt5gPAwUGpewIw0av4Vwym3_UdWkYcjGENBqoyj1-6CCN5sKVvX8PauvWcZc5yCD4OkNt9KC0CuTunLRQ2Ak2tK5qQY97v7iASGHdzzJYnxKpEERI7vyLI6uZmA8

####################

GET http://localhost:250/api/groups/409ace6d-8a63-4f3c-a80d-56d9d28ecf67
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUxMzE2NTYsImV4cCI6MTYzMDMxNTY1Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6ImIwMWVkMWVkLTlmMDYtNGYxMS05MjA1LTExY2JmMzIxOTkzNCIsIm5hbWUiOiJVc2VyIn0.p2TnBsOCyKQ2MvBe1ODtsbRDRpB7FsL0odFQwyUeAevt_iKSMg-MNeNQbLYmtgF4zxzPGgwBlartUIY7Cw7Vp_UUwiBcRAmK8SLZbZpvqyn0fcAGolA9nR-v5ev0yPenKC1iKi7C3K3j7oCwQb44YEKBflnQESSGt6KGeQUXipksO-8Gr9NjAuYe3nPEw_BIlHYw_ju-fnkpgV4r-25jzzxlHZQ20EZuwCi529JbiyyfZMYocqPLUx2u5MmjT0ZaS9SM06752r9JOKYv97Dt3I3lHbytprT6aztNk7DSi27wT2KbkNmXcn_9D4rYFFhUB6Y-FrFGLwq8Zp_BSgljroNpskeWL1ab9i2vblJNvDqbXWc0wVoXtr0Fp_ji71bYM7lK0HXsHTrCzRY61RvaZgbkQbafqnOYFS3A_jGuB8TgyLqJNiwhKw1WNUBYdUt5MDQ4wEwP0j1eI8_5iym8-fe__KlinalEa8MaN6WnfhSYvcAF7LVYPHBVbi1OhLMrV0_94iBd4lcQmMX6rkzMvaw8f6u7HtTc2CmQPVTbtP3OLH9Qt5gPAwUGpewIw0av4Vwym3_UdWkYcjGENBqoyj1-6CCN5sKVvX8PauvWcZc5yCD4OkNt9KC0CuTunLRQ2Ak2tK5qQY97v7iASGHdzzJYnxKpEERI7vyLI6uZmA8

####################

POST http://localhost:250/api/groups/409ace6d-8a63-4f3c-a80d-56d9d28ecf67/photo
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUxMzE2NTYsImV4cCI6MTYzMDMxNTY1Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6ImIwMWVkMWVkLTlmMDYtNGYxMS05MjA1LTExY2JmMzIxOTkzNCIsIm5hbWUiOiJVc2VyIn0.p2TnBsOCyKQ2MvBe1ODtsbRDRpB7FsL0odFQwyUeAevt_iKSMg-MNeNQbLYmtgF4zxzPGgwBlartUIY7Cw7Vp_UUwiBcRAmK8SLZbZpvqyn0fcAGolA9nR-v5ev0yPenKC1iKi7C3K3j7oCwQb44YEKBflnQESSGt6KGeQUXipksO-8Gr9NjAuYe3nPEw_BIlHYw_ju-fnkpgV4r-25jzzxlHZQ20EZuwCi529JbiyyfZMYocqPLUx2u5MmjT0ZaS9SM06752r9JOKYv97Dt3I3lHbytprT6aztNk7DSi27wT2KbkNmXcn_9D4rYFFhUB6Y-FrFGLwq8Zp_BSgljroNpskeWL1ab9i2vblJNvDqbXWc0wVoXtr0Fp_ji71bYM7lK0HXsHTrCzRY61RvaZgbkQbafqnOYFS3A_jGuB8TgyLqJNiwhKw1WNUBYdUt5MDQ4wEwP0j1eI8_5iym8-fe__KlinalEa8MaN6WnfhSYvcAF7LVYPHBVbi1OhLMrV0_94iBd4lcQmMX6rkzMvaw8f6u7HtTc2CmQPVTbtP3OLH9Qt5gPAwUGpewIw0av4Vwym3_UdWkYcjGENBqoyj1-6CCN5sKVvX8PauvWcZc5yCD4OkNt9KC0CuTunLRQ2Ak2tK5qQY97v7iASGHdzzJYnxKpEERI7vyLI6uZmA8

{
  "photo": "/api/photo/a5546729-f7c7-4f65-be61-dde7d1e16c8a"
}

####################

PUT http://localhost:250/api/groups/409ace6d-8a63-4f3c-a80d-56d9d28ecf67
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUxMzE2NTYsImV4cCI6MTYzMDMxNTY1Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6ImIwMWVkMWVkLTlmMDYtNGYxMS05MjA1LTExY2JmMzIxOTkzNCIsIm5hbWUiOiJVc2VyIn0.p2TnBsOCyKQ2MvBe1ODtsbRDRpB7FsL0odFQwyUeAevt_iKSMg-MNeNQbLYmtgF4zxzPGgwBlartUIY7Cw7Vp_UUwiBcRAmK8SLZbZpvqyn0fcAGolA9nR-v5ev0yPenKC1iKi7C3K3j7oCwQb44YEKBflnQESSGt6KGeQUXipksO-8Gr9NjAuYe3nPEw_BIlHYw_ju-fnkpgV4r-25jzzxlHZQ20EZuwCi529JbiyyfZMYocqPLUx2u5MmjT0ZaS9SM06752r9JOKYv97Dt3I3lHbytprT6aztNk7DSi27wT2KbkNmXcn_9D4rYFFhUB6Y-FrFGLwq8Zp_BSgljroNpskeWL1ab9i2vblJNvDqbXWc0wVoXtr0Fp_ji71bYM7lK0HXsHTrCzRY61RvaZgbkQbafqnOYFS3A_jGuB8TgyLqJNiwhKw1WNUBYdUt5MDQ4wEwP0j1eI8_5iym8-fe__KlinalEa8MaN6WnfhSYvcAF7LVYPHBVbi1OhLMrV0_94iBd4lcQmMX6rkzMvaw8f6u7HtTc2CmQPVTbtP3OLH9Qt5gPAwUGpewIw0av4Vwym3_UdWkYcjGENBqoyj1-6CCN5sKVvX8PauvWcZc5yCD4OkNt9KC0CuTunLRQ2Ak2tK5qQY97v7iASGHdzzJYnxKpEERI7vyLI6uZmA8

{
  "name": "edited"
}

####################

DELETE http://localhost:250/api/groups/409ace6d-8a63-4f3c-a80d-56d9d28ecf67
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjUxMzE2NTYsImV4cCI6MTYzMDMxNTY1Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6ImIwMWVkMWVkLTlmMDYtNGYxMS05MjA1LTExY2JmMzIxOTkzNCIsIm5hbWUiOiJVc2VyIn0.p2TnBsOCyKQ2MvBe1ODtsbRDRpB7FsL0odFQwyUeAevt_iKSMg-MNeNQbLYmtgF4zxzPGgwBlartUIY7Cw7Vp_UUwiBcRAmK8SLZbZpvqyn0fcAGolA9nR-v5ev0yPenKC1iKi7C3K3j7oCwQb44YEKBflnQESSGt6KGeQUXipksO-8Gr9NjAuYe3nPEw_BIlHYw_ju-fnkpgV4r-25jzzxlHZQ20EZuwCi529JbiyyfZMYocqPLUx2u5MmjT0ZaS9SM06752r9JOKYv97Dt3I3lHbytprT6aztNk7DSi27wT2KbkNmXcn_9D4rYFFhUB6Y-FrFGLwq8Zp_BSgljroNpskeWL1ab9i2vblJNvDqbXWc0wVoXtr0Fp_ji71bYM7lK0HXsHTrCzRY61RvaZgbkQbafqnOYFS3A_jGuB8TgyLqJNiwhKw1WNUBYdUt5MDQ4wEwP0j1eI8_5iym8-fe__KlinalEa8MaN6WnfhSYvcAF7LVYPHBVbi1OhLMrV0_94iBd4lcQmMX6rkzMvaw8f6u7HtTc2CmQPVTbtP3OLH9Qt5gPAwUGpewIw0av4Vwym3_UdWkYcjGENBqoyj1-6CCN5sKVvX8PauvWcZc5yCD4OkNt9KC0CuTunLRQ2Ak2tK5qQY97v7iASGHdzzJYnxKpEERI7vyLI6uZmA8
