App\Entity\Photo:
  attributes:
    id:
      groups: [ photo_read ]
    archive:
      groups: [ photo_read, photo_create ]
    description:
      groups: [ photo_read, photo_create, photo_update ]
    likes:
      groups: [ photo_read ]
    private:
      groups: [ photo_read, photo_create, photo_update ]
    owner:
      groups: [ photo_read ]
    usersLiked:
      groups: [ photo_read ]
    groups:
      groups: [ photo_read ]
    createdAt:
      groups: [ photo_read ]
    updatedAt:
      groups: [ photo_read ]