
#################################### USERS #########################################

POST http://localhost:250/api/users/register
Content-Type: application/json

{
  "name": "User",
  "email": "user@email.com",
  "password": "User@01"
}

####################

GET http://localhost:250/api/users

####################

GET http://localhost:250/api/users/b01ed1ed-9f06-4f11-9205-11cbf3219934

####################

GET http://localhost:250/api/users/login_check
Content-Type: application/json

{
  "username": "user@email.com",
  "password": "User@01"
}

####################

PUT http://localhost:250/api/users/b01ed1ed-9f06-4f11-9205-11cbf3219934
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjY4NjAzMDUsImV4cCI6MTYyNjg2MzkwNSwicm9sZXMiOlsiUk9MRV9QUkVNSVVNIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6ImIwMWVkMWVkLTlmMDYtNGYxMS05MjA1LTExY2JmMzIxOTkzNCIsIm5hbWUiOiJVc2VyIn0.Dxa7U1lVmAu4hAbj9ttNWZ2bgGVQCnn09dDjCKbwxgD6QNBxkSTykMUSeO4pt6PoFekxinw1vEUv6cDTjLbNkqQwAarICsy1zJ38Iruro0xXebn00NFKbU_nQBK_mapdSlc8i_cqq4SsWsCVsUH4xCEmliLl7rFAj-__045-D4zkuwFtkNVYovSXgywl6E7WSwXUD3Sb5HyKq38Z_N09vHGgFAxmaNWzR_XzKWGjmalMYNF-WLsB_8qSbQfJUuqu2XkWbGFbQ9liivoXDfKTL48r6djhsY5UzNJu0vpC63Vy0WdeEuenwO8LEYMBrTVn_HD3GPzIsAsdtp3Lqpkmx4H1hP5caI2-dRqUPfTrDrWnn-w9k21amiw_F8Y2JR3d9YHy_hpT8VoroMKsEZyG5xCFlut3GL3UyXRZLjAiRfMBbtwnl18tcxNm1dsFy-v_JQZz-YpwowOx99XZoCQd1Sf4IDzJqvqE500czhMMCiLnjvJluCgELh5poUyD7eC-ZGw1kO2QJGXnamRW2HRMto1shyLzZQZGDEXbwpTtkZiFQPwbTaIKF_gYkf-2TGLX8hDk42Xlm86vqR6U7FwGKOYs3pI2gbvCMQg4ziix-c64HWYL0dy5ICRQsyPLb52fj8zcnEKm3HuGHu3athHAVg6aT1APHWfArXkSaOmck-k

{
  "name": "updated"
}
