
#################################### USERS #########################################

POST http://localhost:250/api/users/register
Content-Type: application/json

{
  "name": "User",
  "email": "user@email.com",
  "password": "User@01"
}

####################

GET http://localhost:250/api/users

####################

GET http://localhost:250/api/users/b01ed1ed-9f06-4f11-9205-11cbf3219934

####################

GET http://localhost:250/api/users/login_check
Content-Type: application/json

{
  "username": "user@premium.com",
  "password": "password"
}

####################

PUT http://localhost:250/api/users/b01ed1ed-9f06-4f11-9205-11cbf3219934
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjY5NDg3MDMsImV4cCI6MTYyNjk1MjMwMywicm9sZXMiOlsiUk9MRV9QUkVNSVVNIl0sInVzZXJuYW1lIjoidXNlckBwcmVtaXVtLmNvbSIsImlkIjoiMTEzYWM0N2MtNzNmZi00ZjUxLWI0YjktY2NhZWUxZTNjM2Q0IiwibmFtZSI6IlVzZXJQcmVtaXVtIn0.iDe9Wx0AwY-IvCCtR3y3EdoBWb_pIzeYum-n31SuRmFMj4MxNS57gTyZ7z_8y61P-eF3XfMf-O2KL7InrW-SvYvd0cTL9V8xwVSIB1228-K6wvACt-Wv8xJv8exclEF1pCJ2Rs2QFHtrxC2c13BlQNYQxJftW9wtnAACQXChyOCGhd8QrShfI99gJOwD_l5t02REWaECuYyG86-_KpnD5ykb6QgceO0WoX5YI3ehhdqXJjjNQEkh1C1cPRShNx_atFTjuFTGKq32fkksf-iyEWK-EJASX2ikWXYBdNoH4J3td7hzRZ20ndGy2b4Q7NOUwwDU0HkJMWZ9e29w-iIQySNxpOK8n0kxnv39WIThrQCp7Ra_OKqU7pLpsTGQGRYRaVe4hfxtZKbf-FXoWEYjHY9scp9rjU1C8aGSz6dQQ-YDr7D679-mCHUY13IfgzTJfwskymYuUFFT1v3J5G8STNHsd_cT_ZAr23HoguKzrbxg8m4ITjr8o9IUjtnua9NTU7f5qKcNm0vDilcK_tWX-HAokyBAoWfwIvRjvgRvvOhzgyaPa66_HdK4np4_hQL9QSzePPhiFYtHRcbfct6132IDLUhbbkzm9JDLdw1yNQ1fm66_itVp82ofrn6i-K9QRVYE5nSozKY1oXHUMk-GZiuu81DXbKBCi3Rj7P_dLfw"

{
  "name": "updated"
}
