
#################################### USERS #########################################

POST http://localhost:250/api/users/register
Content-Type: application/json

{
  "name": "User",
  "email": "user@email.com",
  "password": "User@01"
}

####################

GET http://localhost:250/api/users

####################

GET http://localhost:250/api/users/b01ed1ed-9f06-4f11-9205-11cbf3219934

####################

GET http://localhost:250/api/users/login_check
Content-Type: application/json

{
  "username": "user@email2.com",
  "password": "User@01"
}

####################

PUT http://localhost:250/api/users/b01ed1ed-9f06-4f11-9205-11cbf3219934
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MjY2OTI0ODUsImV4cCI6MTYzMTg3NjQ4NSwicm9sZXMiOlsiUk9MRV9QUkVNSVVNIl0sInVzZXJuYW1lIjoidXNlckBlbWFpbC5jb20iLCJpZCI6ImIwMWVkMWVkLTlmMDYtNGYxMS05MjA1LTExY2JmMzIxOTkzNCIsIm5hbWUiOiJVc2VyIn0.YfXq5Nvn9ySjiBaCcOTDPPXQVWwSqZHO5RaYqHhRqYAOL-84WZZSqM-lsvmERm8hx2VPVOx4U7ElM9445i26R-Bxy_1Lz56oMO_KcdbTyAYhsGC9b0L76IOseLWaGKlDp2elIf-nYf52fXJ43jfXxZFxxUSG3Mxo16dlnMMsq-10lWlubmRYeK9SSEA2dMlx_exAkDHTJ1_5gdc5Cg4_-k7gYSV5dAeRPOq-71dN5E9opmia6cmq82ZQtQm3fMZD1QyvNMckn5QrCjPA8viWLXmG7_pFGswbow_IlnXk0vINAOYpFmWU9XfyM0u4VffB_ueO664mL6H4PLsjEB1oTWiSXchciAXWfpcL7KJZzWzXCFMV4sACGDHlphEzXPkiD3d1mjuJsaE1r94QENb8enas7yjwcEqYdphdEEMZesglzFCCF4YMbHdZIs87EJ29JkeYhs8YQEwiBcx3NteEZDF4PnQw_LA9wq3mhGK_xr6wC9BS4NEalOmBbMz8aFWwEEGYI3dDtg3s_KDuQGOn7O1b9VHyOBAP3yQ50twWzPXjsdbA478wf1GQPbceq34AsBo8-GwoppQZXDVYeVIpjV5ZK_PVqv5pIAjsIJGQvpVenVm2CzXBRLxavBTpkB0vsoTJ6CvLbCJKhmXnyXwiSSC1vlA1wVoAojqdUPa-nes

{
  "name": "updated"
}
